version: '3.7'

services:
  origin:
    build: .
    env_file: .env
    ports:
    - "2352:2352/tcp"
    # environment:

    # command: bash -c 'yarn && yarn start'
    command: bash -c 'npm run start'
    volumes:
      - ./:/app